### ISSUE TITLE
Upgrade to KVM

### ISSUE THREAD

**Issue by busla** [robbertkl/RancherOS-Linode#1]
Looks like I need to upgrade the node from XEN to KVM. Is it perhaps missing from the README?

**Comment by busla** [comment]
ohh wait. FINNIX rescue mode?

Well, already upgraded. Let´s see what happens :-)

**Comment by busla** [comment]
Worked.

I would like to clarify a few things in the README and add KVM upgrade notes. Would you mind a PR?

**Comment by robbertkl** [comment]
New Linodes are always provisioned with KVM hypervisor, at least with my account, but it could still be XEN with your account. In any case, Linode will be (slowly) moving away from XEN, first by making it the default for new Linodes, and then also migrating all existing XEN Linodes. For example, their Frankfurt location is already KVM only.

Therefore, in the long run this won't be an issue. What problem did you run into with your XEN Linode? Perhaps the "Direct Disk" kernel mode was not available?

Finally, if you'd like to add an note to the README stating that your Linode has to be migrated to KVM (if it's not yet KVM) before doing the install, I'm always open to PRs. Thanks!

**Comment by busla** [comment]
Just started a node in London and it was XEN. 

Yes, the "Direct disk" was not available so I needed to upgrade the node to KVM.

PR is on the way.

**Comment by robbertkl** [comment]
Fixed in #2.
