### ISSUE TITLE
Blank screen on boot

### ISSUE THREAD

**Issue by ShakataGaNai** [robbertkl/RancherOS-Linode#3]
I hate to file this "issue" but I cannot seem to get this working at all. I setup a new Linode (in Fremont) and followed your directions to the letter. The install script finished, I rebooted... and the lish screen sits black for about 30-60 seconds - then returns to the "nothing is running" screen. 

On my second attempt I took apart your install script and tried to do every step manually (assuming that maybe there was an error I simply wasn't seeing before). No different. I have confirmed that there is a /boot and /var/lib/rancher/conf/cloud-config.d with cloud-config.yml

I wish I had an error message or something, but I'm at a total loss as to how to diagnose this. Have you tried this with 0.4.5 (Since that's the latest)? Am I missing something?

cloud-config.yml for completeness:

<pre>
#cloud-config
ssh_authorized_keys:
  - ssh-rsa keykeykey
rancher:
  network:
    interfaces:
      eth0:
    address: 1.2.3.4/24
    gateway: 1.2.3.1
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4</pre>

Thanks

**Edit**: I installed yet again, this time with -v 0.4.2 (since that example was in the instructions) and I ended up with the same blank screen.

**Comment by robbertkl** [comment]
I believe your cloud-config.yml is incorrect. The indentation for `address` and `gateway` is not enough (should be below eth0). Can you try a cloud-config with only your SSH key (IP should be automatic through DHCP) to see if you can ping the server / login through SSH after the install?

About the blank screen: did you try the graphical console (Glish)?

**Comment by ShakataGaNai** [comment]
I think the indentation error was when it got copied/pasted into Github comment, but now I'm not sure (and of course I'm working from a different machine today).  That being said I reduced the cloudconfig to just the ssh key as you specified and it works.

While I wasn't using the Glish, I think I may have opened it at some point yesterday in my tinkering and that probably didn't help either.

![screen shot 2016-06-24 at 3 24 39 pm](https://cloud.githubusercontent.com/assets/1415068/16352154/384262e0-3a20-11e6-83e6-725768745e2c.png)

Thank you!
