### ISSUE TITLE
Install issue?

### ISSUE THREAD

**Issue by jasmeralia** [robbertkl/RancherOS-Linode#4]
I just tried using this today and the install went ok, but it does not boot up successfully. It either gets stuck on the Grub menu and does not boot, or it boots and then fails shortly afterwards. It's a bit hard to tell using LISH with it being set to a 24x80 configuration. Any more info I can provide, please let me know. 

I'm at a bit of a loss as I had had a server hacked recently, rebuilt it cleanly with Ubuntu Xenial, ensured no root login over ssh, enforced ssh key authentication only, installed docker, launched shipyard, and an email container. All the shipyard ports (and I think ssh?) should have only been accessible via my home IP (or my other Linode VPSes over the private network) with iptables rules that I turned on before installing Docker. I'm not sure how much more secure I can get than that, outside of switching distros, which is why I'm specifically interested in RancherOS.

**Comment by robbertkl** [comment]
Nasty, a hack like that 😞. One thing I would recommend looking into is IPv6: with IPv6 support by cloud providers getting pretty common, Linux distros automatically configuring IPv6 addresses, and services automatically listening on IPv6 as well, many people forget to lock down (or disable) IPv6. Sometimes very strict rules are set in `iptables`, not realizing their `ip6tables` is wide open!

As for the RancherOS install: I'll try to look into it and try some installs myself. Perhaps a recent release of RancherOS won't install using this method anymore, or maybe I need to make some changes to the install script.

I'll get back to you...

**Comment by jasmeralia** [comment]
Actually I think the first time around I had an error in my cloud-config.yml file; after rerunning the setup steps a second time I was able to get things working. One thing that is worthy of note is that Linode support recommended using Glish to connect instead of Lish; they noted that it's better at working with unsupported distros compared to Lish.

I think you're right about IPv6, I think I didn't factor that in and the shipyard setup configures docker-engine access on a TCP port, so that's probably what the issue was; people had carte blanche to launch containers of any configuration over IPv6. I'll definitely have to keep that in mind moving forward, shame on me for not thinking about it in advance. Thanks for mentioning that.
